Milestone 3: Game logic
okikiola11/tic-tac-toe pull request #5
Opened 2020-05-15 09:42 UTC by Mupa1

## What does this PR do?
- It adds the game logic for Tic Tac Toe project

## Description of task completed
- Separated methods into different classes and files
- Added validations for user's names

2020-05-16 02:49 UTC, rOluochKe requested changes
Hello @Mupa1 and @okikiola11 
### You have done a good job so far :clap: However, you can do better before your project could be approved.
- [ ] You can create a game module and put it in the lib. This makes the main.rb file to only call the files and runs the loop making your code easily readable and maintainable
- [ ] When a player wins a game, it is supposed to call the winner's name, not `0`
- [ ] It is also good practice when the game ends, it asks if the players want to continue or quit the game

### Make all these changes and resubmit for another code review. Good luck.
- Happy coding!

By Raymond
slack @iamraymond

2020-05-18 20:52 UTC, pelzolga123 requested changes
The project requires changes.

2020-05-18 20:52 UTC, pelzolga123 commented
## Hi Team,
### Amazing work so far :+1:
Still, there are some more changes required before this Pull Request can be approved: 
* [ ] All classes should be kept in the `lib` directory. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)) You have the PlayGame class inside the `main` file, but all classes should be stored in the `lib` directory. 
* [ ] The code should respect the single responsibility rule for methods (i.e. each method does exactly one thing). Don't create long methods that are doing multiple steps of the game process. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/single_responsibility.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)) You have method `play` in your project, that is pretty big, that should be fixed.

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-05-20 18:45 UTC, majovanilla requested changes
Hi team!

## You did a *great* job on this project! 💜 

There are still some changes 👇 you need to implement to approve this request 🔍
Check the commented code below.

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-05-20 18:45 UTC, majovanilla commented on bin/main.rb
>    end
Great validation! :+1:  you should add a check to prevent both players to have the same name.

2020-05-20 18:45 UTC, majovanilla commented on bin/main.rb
>    end
You are repeating this code for each player. That is not a good practice (see  this article's [Principle 3](https://www.nascenia.com/ruby-on-rails-development-principles/))
You could easily move everything into another method and call it two times.
Remember to avoid `puts` on the `lib` folder when you refactor this code. You can still return a string and then `puts` it on `main.rb`.

2020-05-20 18:45 UTC, majovanilla commented on bin/main.rb
> +    input = @game.input_to_index(gets.chomp)
You don't show which player's turn is. This causes confusion and affects the UX.

2020-05-20 18:45 UTC, majovanilla commented on bin/main.rb
> +        return game_over == true
You have three nested if statements nested in a loop in this method. I strongly suggest people avoid this since it's not efficient and it's difficult to read. If you must use them, I would advise you to create separate methods for each if statement, improving readability.

2020-05-20 18:45 UTC, majovanilla commented on bin/main.rb
> +  play_again
Your method breaks when the user types something else than yes or no. You should validate this and ask for the response again to prevent mistakes.

2020-05-20 18:45 UTC, majovanilla commented on lib/game.rb
> +  # rubocop:enable Metrics/AbcSize, Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
You could improve this method substantially. TIP: try creating an array with all the possible winning combinations and then comparing it to the current board array to see if it `includes` any of them. Use the player's symbol as an argument to the method.

2020-05-20 18:45 UTC, majovanilla commented on lib/game.rb
> +  end
The Game class should have the game logic. It would be better if you create another class to have all the Board related methods, keeping your code more organized.

2020-05-23 09:54 UTC, bolah2009 approved these changes
It's a 👍🏾 from me!

### :heavy_check_mark: Approved!

Check out the optional comments before merging. :relaxed: 

> ### Let's remember about `private` methods, methods that are not used outside of the class should be private methods.

Good luck with your next projects. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2020-05-23 09:54 UTC, bolah2009 commented on lib/game.rb
> +    true unless @board.board_cells.include?(' ')
[Optional]

I think we could use only `!@board.board_cells.include?(' ')` in this case. Or use methods we learn from the `Enumerable Projects`, a good example is the `none?` since this will return true if **none** of the `board_cells` is ` `. e.g. `@board.board_cells.none?(' ')` 🤔

2020-05-23 09:54 UTC, bolah2009 commented on lib/game.rb
> +    true if full_board? || won?
[Optional]

Same with the suggestion above, I think we can return `full_board? || won?`, assuming `won?` will always return a boolean.

2020-05-25 08:20 UTC, Mupa1 commented
Thank you so much for your reviews, especially @majovanilla for your descriptive feedback.

2020-05-25 08:20 UTC, merged